version: "3"
services:
  university-mongo:
    image: mongo:4.0.8
    container_name: university-mongo
    restart: always # unless-stopped
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGODB_DATA_DIR: ${MONGODB_DATA_DIR}
      MONDODB_LOG_DIR: ${MONDODB_LOG_DIR}
    ports:
      - "27017:27017"
    volumes:
      - mongouniversitydbdata:${MONGODB_DATA_DIR}
  university-web:
    build: .
    container_name: university-web
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    environment:
      FLASK_ENV: development
volumes:
  mongouniversitydbdata: